feat: Ability to collapse/expand table to simplify the visualization
BOCOVO/db-schema-visualizer pull request #52
Opened 2024-07-16 15:27 UTC by tv-long

@BOCOVO 
Please check my changes according to the issue #49

2024-07-17 20:21 UTC, BOCOVO commented
> @BOCOVO Please check my changes according to the issue #49

Hello @tv-long . 
I'm very happy to see this PR.
Thank you very much for working on the feature.

I'll take a look at it as soon as possible, and then we'll release that 🚀

2024-07-21 11:18 UTC, BOCOVO requested changes
I've tested it, and it works well. However, I have left a small suggestion for change, mainly in the text.

2024-07-21 11:18 UTC, BOCOVO commented on packages/json-table-schema-visualizer/src/providers/TableDetailLevelProvider.tsx
> +  const [state, setState] = useState(detailLevelStore.getCurrentDetailLevel());
A title suggestion
```suggestion
  const [state, setState] = useState( () => detailLevelStore.getCurrentDetailLevel() );
```
The advantage is that the `detailLevelStore.getCurrentDetailLevel` will be called only once. At the first rendering React will call it to get the initial value. For the subsequent rendering, React will no longer call it.

2024-07-21 11:18 UTC, BOCOVO commented on packages/json-table-schema-visualizer/src/types/tabelDetailLevel.ts
I think that you meant `tableDetailLevel`.
> [!NOTE]
> I'm talking about the file name.

2024-07-24 13:46 UTC, tv-long commented
@BOCOVO 
I made changes according to your feedback
Please check

2024-07-24 19:26 UTC, BOCOVO commented
Thank you very much @tv-long.

I'm going to merge these, and we'll publish them this very evening 🔥 .

2024-07-24 19:28 UTC, BOCOVO approved these changes

2024-07-24 19:41 UTC, BOCOVO commented
close: #49

2024-07-24 19:41 UTC, merged